### ISSUE TITLE
Cant send GET request with content

### ISSUE THREAD

**Issue by mathew-odwyer** [Mako88/SimpleHttpClient#15] opened 2023-11-28 04:11 UTC
Take the following signature in my API:

```csharp
[HttpGet]
public async Task<FetchLocationsFromTextResponseDTO> FetchLocationFromText([FromQuery] FetchLocationsFromTextRequestDTO dto)
```

On the client side, I cannot make the request as `request.Location` is null.

```csharp
var request = new SimpleRequest(url, method, content);
var response = await this.client.MakeRequest<FetchLocationsFromTextResponseDTO>(request).ConfigureAwait(false);

return response.Body;
```

**Comment by Mako88** [comment] 2023-11-28 22:38
What version of SimpleHttpClient are you using? I'm not able to reproduce the issue in the latest version (sending a GET request with a body is working fine for me). I did notice though that your server is expecting to extract the dto from the query string, but you're sending `content` as the body. To send query strings, use the `request.QueryStringParameters` dictionary.

**Comment by Mako88** [comment] 2024-04-18 16:31
I'm going to go ahead and close this for now, but definitely let me know if you still have an issue!

**Closed as completed by Mako88** 2024-04-18 16:31 UTC
